### ISSUE TITLE
Data set loading problem

### ISSUE THREAD

**Issue by huke3014** [ciderpark/Libtorch_YOLOv3_train_demo#2]
float c, x, y, w, h, b = 0.0;
		while (true)
		{
			stream_l >> c >> x >> y >> w >> h;
			if (stream_l.eof())
				break;
			label.push_back({ b, c, x, y, w, h });
		}
Why add b variable?What's the use?

**Comment by ciderpark** [comment]
b means batch here. I use it for convenience in StackAndCat() function.

**Comment by huke3014** [comment]
> b表示此处是批处理。为了方便在StackAndCat（）函数中使用它。

Thank you very much for your reply. I'm working hard on the source code. Good luck.

**Comment by huke3014** [comment]
Thank you very much for your reply. I'm working hard on the source code. Good luck.
