### ISSUE TITLE
net->forward() Related issues

### ISSUE THREAD

**Issue by huke3014** [ciderpark/Libtorch_YOLOv3_train_demo#3]
....
torch::Tensor* null_t = NULL;
x = seq_imp->forward(x, inp_dim, num_classes, *_device, torch::tensor({ 0 }), null_t);
delete null_t;
....
Why do you do this？
x = seq_imp->forward(x, inp_dim, num_classes, *_device);
Can't that be done？

**Comment by ciderpark** [comment]
Hi, I have tried this before, if u want use default arguments in forward(), u need to add those after forward(...){...}:
torch::Tensor* a = NULL;
FORWARD_HAS_DEFAULT_ARGS({4, torch::nn::AnyValue(torch::tensor({0}))}, {5, torch::nn::AnyValue(a)})

**Comment by ciderpark** [comment]
Hi, I have tried this before, if u want to use default arguments in forward(), u need to add those after forward(...){...}:
torch::Tensor* a = NULL;
FORWARD_HAS_DEFAULT_ARGS({4, torch::nn::AnyValue(torch::tensor({0}))}, {5, torch::nn::AnyValue(a)})

**Comment by ciderpark** [comment]
Hi, I have tried this before, if u want to use default arguments in forward(), u need to add these two lines after forward(...){...}:
torch::Tensor* a = NULL;
FORWARD_HAS_DEFAULT_ARGS({4, torch::nn::AnyValue(torch::tensor({0}))}, {5, torch::nn::AnyValue(a)})
