### ISSUE TITLE
Microsoft C++ exception: std::bad_alloc

### ISSUE THREAD

**Issue by wz940216** [ciderpark/Libtorch_YOLOv3_train_demo#4]
HI,
  I tried to compile your code using windows10 and VS2019, using the release mode. An error **_Microsoft C++ exception: std::bad_alloc_** occurred during debugging. Could you help me to sove this questions?

Best wishes！

**Comment by ciderpark** [comment]
> HI,
> I tried to compile your code using windows10 and VS2019, using the release mode. An error **_Microsoft C++ exception: std::bad_alloc_** occurred during debugging. Could you help me to sove this questions?
> 
> Best wishes！

Could you provide more information about the error and the env?

**Comment by wz940216** [comment]
libtorch 1.6

opencv opencv_world342.lib

cuda11.1

I run`cmake -DCMAKE_PREFIX_PATH=D:\opencv\build\x64\vc15\lib;D:\libtorch -DCMAKE_BUILD_TYPE=Release-G"Visual Studio 16 2019" ../src`to build the code with win10 system.

And I regenerated the release project in the vs2019 project. When I debug the code, the program does not stop at the breakpoint on the first line of the main function. The output error of vs2019 is as follows:

`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\yolov3-libtorch.exe”。已加载符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\c10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\torch_cuda.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“D:\opencv\build\x64\vc15\bin\opencv_world342.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvcp140.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\torch_cpu.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\bcryptprimitives.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\c10_cuda.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cusparse64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\curand64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cusolver64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140_1.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\nvToolsExt64_1.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cudnn64_7.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\comdlg32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cufft64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cublas64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\libiomp5md.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvfw32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\avifil32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\windows.storage.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\profapi.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\avicap32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\umpdc.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\fbgemm.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\cryptsp.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1440_none_73b6d8b6d812b8c6\comctl32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cublasLt64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmm.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msacm32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\asmjit.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\concrt140.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mfplat.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mf.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mfreadwrite.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmmbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmmbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmmbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已卸载“C:\Windows\System32\winmmbase.dll”`
`“yolov3-libtorch.exe”(Win32): 已卸载“C:\Windows\System32\winmmbase.dll”`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mfcore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\crypt32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msasn1.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\DXCore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ksuser.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\cryptbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\dbghelp.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\RTWorkQ.dll”。`
`0x00007FFDF8B53B29 处(位于 yolov3-libtorch.exe 中)引发的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000822E8FF710 处。`
`0x00007FFDF8B53B29 处(位于 yolov3-libtorch.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000822E8FF710 处。`

**Comment by wz940216** [comment]
libtorch 1.6

opencv opencv_world342.lib

cuda11.1

I run`cmake -DCMAKE_PREFIX_PATH=D:\opencv\build\x64\vc15\lib;D:\libtorch -DCMAKE_BUILD_TYPE=Release-G"Visual Studio 16 2019" ../src`to build the code with win10 system.

And I regenerated the release project in the vs2019 project. When I debug the code, the program does not stop at the breakpoint on the first line of the main function. The output error of vs2019 is as follows:

`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\yolov3-libtorch.exe”。已加载符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\c10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\torch_cuda.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“D:\opencv\build\x64\vc15\bin\opencv_world342.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvcp140.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\torch_cpu.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\bcryptprimitives.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\c10_cuda.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cusparse64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\curand64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cusolver64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140_1.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\nvToolsExt64_1.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cudnn64_7.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\comdlg32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cufft64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cublas64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\libiomp5md.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msvfw32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\avifil32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\windows.storage.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\profapi.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\avicap32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\umpdc.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\fbgemm.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\cryptsp.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.1440_none_73b6d8b6d812b8c6\comctl32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\cublasLt64_10.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmm.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msacm32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“F:\workspace\Daheng\libtorch_yolov3\Libtorch_YOLOv3_train_demo-master\build\Release\asmjit.dll”。模块已生成，不包含符号。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\concrt140.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mfplat.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mf.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mfreadwrite.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmmbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmmbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\winmmbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已卸载“C:\Windows\System32\winmmbase.dll”`
`“yolov3-libtorch.exe”(Win32): 已卸载“C:\Windows\System32\winmmbase.dll”`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\mfcore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\crypt32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\msasn1.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\DXCore.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\ksuser.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\cryptbase.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\dbghelp.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。`
`“yolov3-libtorch.exe”(Win32): 已加载“C:\Windows\System32\RTWorkQ.dll”。`
`0x00007FFDF8B53B29 处(位于 yolov3-libtorch.exe 中)引发的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000822E8FF710 处。`
`0x00007FFDF8B53B29 处(位于 yolov3-libtorch.exe 中)有未经处理的异常: Microsoft C++ 异常: std::bad_alloc，位于内存位置 0x000000822E8FF710 处。`
